export const ACTION = {
    UPLOAD_IMAGE: "UPLOAD_IMAGE",
    DELETE_IMAGE : "DELETE_IMAGE",
    UPDATE_USER_DETAILS: "UPDATE_USER_DETAILS",
    VIEW_PROFILE: "VIEW_PROFILE",
    CHANGE_PASSWORD: "CHANGE_PASSWORD",
    FORGOT_PASSWORD_EMAIL:"FORGOT_PASSWORD_EMAIL"
}